all_factions = Faction.create(name: 'Les deux factions')
alliance = Faction.create(name: 'Alliance')
horde = Faction.create(name: 'Horde')

worgen = Race.create(name: 'Worgen', faction_id: alliance.id)
draenei = Race.create( name: 'Draeneï', faction_id: alliance.id)
nain = Race.create(name: 'Nain', faction_id: alliance.id)
gnome = Race.create(name: 'Gnome', faction_id: alliance.id)
humain = Race.create(name: 'Humain', faction_id: alliance.id)
elfe_de_la_nuit = Race.create(name: 'Elfe de la nuit', faction_id: alliance.id)
pandaren = Race.create(name: 'Pandaren', faction_id: all_factions)
gobelin = Race.create(name: 'Gobelin', faction_id: horde.id)
elfe_de_sang = Race.create(name: 'Elfe de sang', faction_id: horde.id)
orc = Race.create(name: 'Orc', faction_id: horde.id)
tauren = Race.create(name: 'Tauren', faction_id: horde.id)
troll = Race.create(name: 'Troll', faction_id: horde.id)
mort_vivant = Race.create(name: 'Mort vivant', faction_id: horde.id)